version: "3.0"
debug: true
testing: false
csrf_enabled: true
secret_key: 'thisissecret'
sqlalchemy_database_uri: "postgresql:///flask_dropbox"
upload_folder: '/home/mikita/WebstormProjects/tutorial/public/files'
allowed_extensions: ['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif']
apispec_swagger_url: '/swagger'
max_file_size: 1024+1
sqlalchemy_track_modifications: true